version: '3'

services:
  api:
    container_name: microservice-checkout
    build: 
      context: ./
      dockerfile: Dockerfile
    image: murilohenzo/microservice-checkout
    entrypoint: dockerize -wait tcp://db:5432 -timeout 30s 
    depends_on:
      - db
    command: yarn dev
    ports:
      - 9090:9090
    links:
      - db